services:
  - type: web
    name: ai-hospital-booking
    env: python
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ai-hospital-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: ai-hospital-redis
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: GOOGLE_AI_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false

databases:
  - name: ai-hospital-db
    plan: starter
    databaseName: hospital_booking
    user: hospital_user

services:
  - type: redis
    name: ai-hospital-redis
    plan: starter
    ipAllowList: []